---
name: PR tests

on: pull_request

jobs:
  static:
    name: 'Syntax validation'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: puppet/puppet-dev-tools:4.x
    steps:
      - uses: actions/checkout@v2
      - name: Run static validations
        run: /usr/local/bin/pdk bundle exec rake validate lint check
        env:
          BUNDLE_WITHOUT: development:system_tests:release

  unit:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container: puppet/puppet-dev-tools:4.x
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests on current puppet
#        run: /usr/local/bin/pdk bundle exec rake spec
        run: /usr/local/bin/pdk test unit
        env:
          BUNDLE_WITHOUT: development:system_tests:release
      - name: Run unit tests on Puppet 6
        run: /usr/local/bin/pdk test unit  --puppet-version=6
        env:
          BUNDLE_WITHOUT: development:system_tests:release
      - name: Run unit tests on Puppet 5
        run: /usr/local/bin/pdk test unit --puppet-version=5
        env:
          BUNDLE_WITHOUT: development:system_tests:release
        continue-on-error: true
